### ISSUE TITLE
reclassify edgewater towers as venue

### ISSUE THREAD

**Issue by skorasaurus** [skorasaurus/quiencle#1]
it's an apartment building

**Comment by nvkelso** [comment]
Sometimes if it's a huge apartment building complex we'll set an `mz:is_landuse_aoi=1` value on it (keeping as a neighbourhood).

**Comment by skorasaurus** [comment]
@nvkelso: 

Thanks for the info. ET is within [another neighborhood](https://en.wikipedia.org/wiki/Lakewood_Gold_Coast) (not yet on whosonfirst). We can talk about it more as I submit a first draft, likely in the next day or 2.

**Comment by skorasaurus** [comment]
fixed in https://github.com/skorasaurus/quiencle/commit/ef28b62ba22dbdc670a366c36dd760cb038636c5

**Comment by skorasaurus** [comment]
and https://github.com/skorasaurus/quiencle/commit/0c22838fbf5b889ddb3ae73701aa60c12a06bad3
